### ISSUE TITLE
Ability to use 'index.js' as the root for a directory

### ISSUE THREAD

**Issue by stevie-mayhew** [Tom-Alexander/markdown-docs#2]
There should be a configuration setting allowing a certain file name to become the root for a directory, and be the link when clicked on in the navigation

**Comment by Tom-Alexander** [comment]
The root node in the navigation will now transition to index.md. It also extracts the title from that file and uses it as the label.

**Comment by stevie-mayhew** [comment]
Thanks @Tom-Alexander !
